### ISSUE TITLE
Create CI Workflow to run adam and display R scripts in 

### ISSUE THREAD

**Issue by bms63** [RConsortium/submissions-pilot3-adam#68]
Create a workflow to run R scripts in proper order

**Comment by thomas-neitmann** [comment]
Looking in to using https://github.com/ropensci/targets.

**Comment by bms63** [comment]
```
name: Batch Run Submission
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  generate-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checkout branch into the runner
      - uses: r-lib/actions/setup-r@master # Set up R runtime
        with:
          r-version: '4.2'
          
      - name: Setup renv # Set up R env to install packages
        run: |
          install.packages('remotes')
          remotes::install_github("rstudio/renv")
        shell: Rscript {0}
        
      - uses: actions/cache@v2 # Cache packages so won't be compiled everytime job is run
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      - name: Install dependencies 
        run: renv::restore()
        shell: Rscript {0}
  
      - name: Execute Production  
        run: source("submission/programs/adsl.R")
               source("submission/programs/adae.R")
               ...
       - name:  Execute QC
               source("qc/submission/programs/qc_adsl.R")
               ...
       - name:  Execute TLFs
               source("vignettes/tlf_primary.Rmd)
               ...      
        shell: Rscript {0}
      
      - name: Commit files # Commit changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git diff-index --quiet HEAD || (git commit -m "update data" && git push)
```
